[project]
name = "robots-on-a-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.6",
    "gymnasium[mujoco]>=1.0.0",
    "stable-baselines3[extra]>=2.4.0",
    "uvicorn>=0.34.0",
]
